### ISSUE TITLE
Could not resolve "...". Maybe you need to "bun install"?

### ISSUE THREAD

**Issue by kaibagley** [Aylur/dotfiles#200]
Hey,

Thanks for making my computer look beautiful.

I recently upgraded ags, and your dots, and am now getting the error in the title. Here is the output on the console after running `ags`:

```
(com.github.Aylur.ags:86949): Gjs-Console-CRITICAL **: 11:14:26.636: 1 | import "lib/session"
           ^
error: Could not resolve: "lib/session". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:1:8

2 | import "lib/init"
           ^
error: Could not resolve: "lib/init". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:2:8

3 | import "style/style"
           ^
error: Could not resolve: "style/style". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:3:8

4 | import options from "options"
                        ^
error: Could not resolve: "options". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:4:21

5 | import Bar from "widget/bar/Bar"
                    ^
error: Could not resolve: "widget/bar/Bar". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:5:17

6 | import Launcher from "widget/launcher/Launcher"
                         ^
error: Could not resolve: "widget/launcher/Launcher". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:6:22

7 | import NotificationPopups from "widget/notifications/NotificationPopups"
                                   ^
error: Could not resolve: "widget/notifications/NotificationPopups". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:7:32

8 | import OSD from "widget/osd/OSD"
                    ^
error: Could not resolve: "widget/osd/OSD". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:8:17

9 | import Overview from "widget/overview/Overview"
                         ^
error: Could not resolve: "widget/overview/Overview". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:9:22

10 | import PowerMenu from "widget/powermenu/PowerMenu"
                           ^
error: Could not resolve: "widget/powermenu/PowerMenu". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:10:23

11 | import ScreenCorners from "widget/bar/ScreenCorners"
                               ^
error: Could not resolve: "widget/bar/ScreenCorners". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:11:27

12 | import SettingsDialog from "widget/settings/SettingsDialog"
                                ^
error: Could not resolve: "widget/settings/SettingsDialog". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:12:28

13 | import Verification from "widget/powermenu/Verification"
                              ^
error: Could not resolve: "widget/powermenu/Verification". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:13:26

14 | import { forMonitors } from "lib/utils"
                                 ^
error: Could not resolve: "lib/utils". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:14:29

15 | import { setupQuickSettings } from "widget/quicksettings/QuickSettings"
                                        ^
error: Could not resolve: "widget/quicksettings/QuickSettings". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:15:36

16 | import { setupDateMenu } from "widget/datemenu/DateMenu"
                                   ^
error: Could not resolve: "widget/datemenu/DateMenu". Maybe you need to "bun install"?
    at /home/kai/.config/ags/main.ts:16:31
```

I have updated to the latest bun, ags-gtk-shell-git, and dotfiles. I'm on Arch.

I can see the 

> Maybe you need to "bun install"?

However I'm not sure how to use this...

Thanks so much!

**Comment by blacklightpy** [comment]
Did you install the TypeScript Transpiler and Dart Sass Transpiler?

`pacman -S dart-sass typescript`.

I used `npm install -g typescript sass` on Void Linux.

I'm also using ESBuild instead of Bun, so I don't know if it's a Bun problem.

**Comment by blacklightpy** [comment]
There is also an option to use ESBuild (he added it since I'm on Void Linux, without Bun support).

Try `AGS_BUNDLER=esbuild ags`

**Comment by Aylur** [comment]
the error suggests that the subdirectories are missing, try deleting the dotfiles and cloning again

**Comment by kaibagley** [comment]
Yep, re-cloning solved it.. Thanks a lot!
